// <auto-generated />
using System;
using FHSaverMVC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FHSaverMVC.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230427133451_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FHSaverMVC.Models.Folder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentFolderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Creating Digital Images"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Recources",
                            ParentFolderId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Evidence",
                            ParentFolderId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Graphic Products",
                            ParentFolderId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Primary Sources",
                            ParentFolderId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Secnadary Sources",
                            ParentFolderId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Process",
                            ParentFolderId = 4L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Final Product",
                            ParentFolderId = 4L
                        });
                });

            modelBuilder.Entity("FHSaverMVC.Models.Folder", b =>
                {
                    b.HasOne("FHSaverMVC.Models.Folder", "ParentFolder")
                        .WithMany("Children")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("FHSaverMVC.Models.Folder", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
